# Generated by Django 3.1.4 on 2021-01-20 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DineOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=250)),
                ('restaurant_id', models.CharField(max_length=1000)),
                ('image_url', models.CharField(max_length=2000)),
                ('restaurant_url', models.CharField(max_length=2000)),
                ('date', models.DateField(blank=True, null=True)),
                ('rating', models.BooleanField(default=True)),
            ],
        ),
    ]
