# Generated by Django 3.1.4 on 2021-01-20 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210115_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineout',
            name='restaurant_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
