# Generated by Django 3.1.4 on 2021-01-07 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dineout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
