# Generated by Django 3.1.4 on 2021-01-14 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210114_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
