# Generated by Django 3.1.4 on 2021-01-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210114_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='frequeny',
            new_name='frequency',
        ),
    ]
