# Generated by Django 3.1.4 on 2021-01-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210114_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='categories',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
